spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/articleutil?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true

  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

file:
  upload:
    dir: ${user.dir}/upload
