spring:
  datasource:
    driver-class-name: com.
    username: root
    password: 123456
    url: jdbc:mysql://localhost/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true

file:
  upload:
    dir: ${user.dir}/upload