spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB

file:
  upload:
    dir: ${user.dir}/upload


